export function writeParagraph() {
  const p = document.createElement('p');
  p.innerText = 'This web application is powered and generated by Webpack 4. The JavaScript is written in modules. There are no physical HTML files; everything is generated by the Webpack bundler.';
  document.querySelector('main').appendChild(p);
}

export function writeHeading() {
  const h1 = document.createElement('h1');
  h1.innerText = "Welcome to Mina's Book Catalogue!";
  document.querySelector('main').appendChild(h1);
}
